---
model:
  type: 
    # - kgmc
    # - autoencoder
    # - ATTENTION
    # - igmc
    - mccl
    # - kgmc_sage
  hop: 1
  in_nfeats: 32
  out_nfeats: 32
  in_efeats: 32
  out_efeats: 32
  latent_dims:
    - 32
    - 32
    - 32
    - 32
  num_heads: 4
  num_relations: 8
  edge_dropout: 0.2
  
dataset:
  keyword_edge_k: 5
  # item_cooc_edge_df: item_keybert
  # user_cooc_edge_df: user_keybert
  # user_item_cooc_edge_df: user_item_keybert
  item_cooc_edge_df: None
  user_cooc_edge_df: None
  user_item_cooc_edge_df: None
  # user_item_cooc_edge_df: 

train:
  device: 0
  epochs: 60
  batch_size: 128
  learning_rates:
    # - 1e-4
    - 1e-3
    # - 1e-2
    # - 2e-3
    # - 5e-3

  weight_decay: 0.0
  lr_decay_step: 10
  lr_decay_factor: 0.90
  log_interval: 200
  log_dir: log
  ndcg_k: 10


